<?php
  $en = array(
    // Header
    'Home' => 'Home' ,
    'Evaluation' => 'Evaluation' ,
    'About' => 'This Area For Telling People Information About Your Hotel Like Address, Building Information, Features And Services
    We are delighted to welcome you at Safir Hotel Homs,Our aim is to ensure that your visit is amemorable and enjoyable one, our dedicated team will spare every effort to provide you with all assistance required during your stay, whether it is business or pleasure .
    You Will feel comfortable & family atmosphere when you step into one of your 92 rooms, All our rooms & suites are heated & air conditioned, international telephone line, radio,tv,satellite,mini bar,in room safe,hair dryer.' ,
    'Language' => 'Language' ,
    'LogIn' => 'LogIn',
    'Menu' => 'Menu',
    'ControlPanel' => 'Control Panel',
    'Employees' => 'Employees',
    'Floors' => 'Floors',
    'Features' => 'Features',
    'Services' => 'Services',
    'Clients' => 'Clients',
    'Logout' => 'Logout',
    'SignIn' => 'Sign In',
    'ChangePassword' => 'Change Password',
    'SiteStyle' => 'Site Style',
    'SiteSettings' => 'Site Settings',
    'English' => 'English',
    'Arabic' => 'Arabic',

    // Admin Index Page
    'Settings' => 'Settings',
    'Total' => 'Total ',
    'MoreDetails' => 'More Details',

    // settings And Processes
    'Phone' => 'Phone',
    'Email' => 'Email',
    'MyProfile' => 'My Profile',
    'Show' => 'Show',
    'Edit' => 'Edit',
    'Delete' => 'Delete',
    'Block' => 'Block',
    'UnBlock' => 'UnBlock',
    'Add' => 'Add',
    'TableTheme' => 'Table Theme',
    'SiteInformation' => 'Site Information',
    'Manage' => 'Manage ',
    'First' => 'First',
    'Next' => 'Next',
    'Last' => 'Last',
    'cell' => 'cell',
    'DefaultColor' => 'Default Color',
    'Transparent' => 'Transparent',
    'LigthBlue' => 'Ligth Blue',
    'Grey' => 'Grey',
    'lightGreen' => 'light Green',
    'LightRed' => 'Light Red',
    'LightYellow' => 'Light Yellow',
    'LightTeal' => 'Light Teal',
    'Light' => 'Light',
    'PageColorChange' => 'Page Color Change',
    'ElementColorChange' => 'Element Color Change',
    'ChangeMainFontColor' => 'Change Main Font Color',
    'SecondaryFontColorChange' => 'Secondary Font Color Change',
    'ChangeFieldBackground' => 'Change Field Background',
    'ChangeLogo' => 'Change Logo',
    'EnglishHotelName' => 'English Hotel Name',
    'ArabicHotelName' => 'Arabic Hotel Name',
    'ChooseYourColor' => 'Choose Your Color',
    'AboutUs' => 'About Us',
    'HotelImages' => 'Hotel Images',
    'EnglishAboutHotel' => 'English About Hotel',
    'ArabicAboutHotel' => 'Arabic About Hotel',
    'DropFilesHereOrClickToUpload' => 'Drop Files Here Or Click To Upload',
    'RemoveFile' => 'Remove File',

    // Admin Floors Page
    'Floor' => 'Floor',
    'FloorId' => 'Floor ID',
    'FlatCount' => 'Flat Count',
    'AddedBy' => 'Added By',
    'Processes' => 'Processes',
    'NewFloor' => 'New Floor',
    'RemoveAFloor' => 'Remove A Floor',
    'Warning:AreYouSureAboutThat' => 'Warning: Are You Sure About That',
    'AddNow' => 'Add Now',

    // Flat Admin Page
    'Flats' => 'Flats',
    'Flat' => 'Flat',
    'FlatId' => 'Flat ID',
    'AddFlat' => 'Add Flat',
    'RoomsCount' => 'Rooms Count',
    'BedsCount' => 'Beds Count',
    'View' => 'View',
    'FlatArea' => 'Flat Area',
    'NewFlat' => 'New Flat',
    'North' => 'North',
    'East' => 'East',
    'South' => 'South',
    'West' => 'West',
    'NorthEast' => 'North East',
    'EastSouth' => 'East South',
    'SouthWest' => 'South West',
    'WestNorth' => 'West North',
    'MainImage' => 'Main Image',
    'OtherImage' => 'Other Image',
    'Close' => 'Close',
    'Save' => 'Save',
    'Warning' => 'Warning',
    'Quantity' => 'Quantity',
    'Warning:NoHotelFeaturesHaveBeenIntroducedYet' => 'Warning: No Hotel Features Have Been Introduced Yet',
    'FlatFeatures' => 'Flat Features:',
    'Rooms' => 'Rooms',
    'Bathrooms' => 'Bathrooms',
    'Beds' => 'Beds',
    'Warning:NoPrimaryFeaturesHaveBeenSelectedYet.' => 'Warning: No Primary Features Have Been Selected Yet.',

    // Features Admin Page
    'NewFeature' => 'New Feature',
    'AddFeature' => 'Add Feature',
    'EditFeature' => 'Edit Feature',
    'FeatureId' => 'Feature ID',
    'FeatureName' => 'Feature Name',
    'Details' => 'Details',
    'Price' => 'Price',
    'LowPrice' => 'Low Price',
    'HeighPrice' => 'Heigh Price',
    'Room' => 'Room',
    'Bath' => 'Bath',
    'Bed' => 'Bed',
    'TV' => 'TV',
    'AC' => 'AC',
    'Stove' => 'Stove',
    'Oven' => 'Oven',
    'Fridge' => 'Fridge',
    'Laundry' => 'Laundry',
    'Cooler' => 'Cooler',
    'ThisFeatureIsExsist' => 'This Feature Is Exsist',
    'TheFeatureUsedInTheFlatCannotBeDeleted' => 'The Feature Used In The Flat Cann\'t Be Deleted',

    // Employees Page
    'EmpId' => 'Employee ID',
    'NewEmployee' => 'New Employee',
    'EditEmployee' => 'Edit Employee',
    'ThisUserNameIsExsist' => 'This UserName Is Exsist',

    // Services Page
    'ServiceId' => 'Service Id',
    'ServiceName' => 'Service Name',
    'NewService' => 'New Service',
    'ThisServiceIsExsist' => 'This Service Is Exsist',

    // LogIn Page
    'UserName' => 'UserName',
    'Password' => 'Password',
    'Sorry:ThereIsAnErrorInTheUserNameOrPassword' => 'Sorry: There Is An Error In The UserName Or Password',

    // NotFound Page
    'notFound' => 'Not Found',
    'Error' => 'Error',
    'GoBack' => 'Go Back',
    'ThePageYouWereLookingForDoesNotExist,TheAddressMayBeMisspelled,OrThePageMayHaveBeenMovedOrDeleted.' => 'The Page You Were Looking For Does Not Exist, The Address May Be Misspelled, Or The Page May Have Been Moved Or Deleted.',
    'ThePageDoesNotExist' => 'The Page Does Not Exist',

    //Table
    'Search' => 'Search',
    'ElemnetsOnEachPage' => 'Elemnets On Each Page',
    'ThereAreNoResult' => 'No results found',
    'From' => 'From',
    'OutOf' => 'Out Of',
    'Records' => 'Records',
    'Searched' => 'Searched',

    // Home Page
    'Hotel' => 'Hotel',
    'HomePage' => 'Home Page',
    'NotRated' => 'Not Rated',
    'All' => 'All',
    'Rate' => 'Rate',
    'Search' => 'Search',

    // Single Flat Page
    'BookingNow' => 'Booking Now',
    'NationalId' => 'National Id',
    'IDImage' => 'ID Image',
    'ChangeAccountImage' => 'Change Account Image',
    'FlatRates' => 'Flat Rates',
    'EntryDate' => 'Entry Date',
    'ExitDate' => 'Exit Date',
    'ReadMore' => 'Read More',
    'ReadLess' => 'Read Less',
    'Cancel' => 'Cancel',
    'FlatInformation' => 'Flat Information',
    'FlatInfo' => 'Flat Info:',
    'FlatImages' => 'Flat Images:',
    'BookingDone' => 'Booking Done',
    'BookingWait' => 'Booking Wait',
    'ThisFlatIdIsAlreadyExistOnThisFloor' => 'This Flat Id Is Already Exist On This Floor',

    // Footer
    'HotelName' => 'Daarna Hotel',
    'InformationAboutTheCompany' => 'information about the company',
    'Help' => 'Help',
    'InformationOffice' => 'Information Office',
    'InvestorRelations' => 'Investor Relations',
    'LearnHowAWebsiteWorks' => 'Learn How A Website Works',
    'TermsAndConditions' => 'Terms And Conditions',
    'LegalInformation' => 'Legal Information',
    'PrivacyNotice' => 'Privacy Notice',
    'SiteMap' => 'Site Map',
    'Copyrights' => 'Copyrights',
    'AllRightsAreSave' => 'All Rights Are Save',
  );
  $ar = array(
    // Header
    'Home' => 'الصفحة الريئسية' ,
    'Evaluation' => 'تقييم' ,
    'About' => 'هذه المساحة لكي تخبر الناس معلومات حول فندقك مثل العنوان, معلومات عن البناء, الميزات والخدمات 
    يسعدنا أن نرحب بكم في فندق سفير حمص , هدفنا أن نجعل زيارتكم ممتعة ولاتنسى .
    سيبذل فريقنا المتفاني كل الجهد لمنحكم المساعدة المطلوبة خلال اقامتكم سواء كانت للعمل او للترفيه .
    ستشعر بالراحة والجو العائلي أثناء اقامتكم في واحدة من الغرف ال 92
    جميع الغرف مجهزة بمكيف هواء للتبريد والتدفئة , خط الاتصال دولي , راديو , تلفزيون , محطات فضائية ,بار صغير , خزنة داخل الغرفه ,مجفف شعر .' ,
    'Language' => 'اللغة' ,
    'LogIn' => 'تسجيل الدخول',
    'Menu' => 'القائمة',
    'ControlPanel' => 'لوحة التحكم',
    'Employees' => 'الموظفين',
    'Floors' => 'الطوابق',
    'Features' => 'الميزات',
    'Services' => 'الخدمات',
    'Clients' => 'الزبائن',
    'Logout' => 'تسجيل الخروج',
    'SignIn' => 'نافذة التسجيل',
    'ChangePassword' => 'تغير كلمة المرور',
    'SiteStyle' => 'نمط الموقع',
    'SiteSettings' => 'إعدات الموقع',
    'English' => 'أجنبية',
    'Arabic' => 'عربية',

    // Admin Index Page
    'Settings' => 'الإعدادات',
    'Total' => 'مجموع ',
    'MoreDetails' => 'المزيد من التفاصيل',

    // settings And Processes
    'Phone' => 'هاتف',
    'Email' => 'بريد الالكتروني',
    'MyProfile' => 'الملف الشخصي',
    'Show' => 'عرض',
    'Edit' => 'تعديل',
    'Delete' => 'حذف',
    'Block' => 'حظر',
    'UnBlock' => 'فك حظر',
    'Add' => 'إضافة',
    'TableTheme' => 'سمات الجدول',
    'SiteInformation' => 'معلومات الموقع',
    'Manage' => 'إدارة ',
    'First' => 'الأول',
    'Next' => 'التالي',
    'Last' => 'الأخير',
    'cell' => 'خلية',
    'DefaultColor' => 'اللون الإفتراضي',
    'Transparent' => 'شفاف',
    'LigthBlue' => 'أزرق فاتح',
    'Grey' => 'رمادي',
    'lightGreen' => 'أخضر فاتح',
    'LightRed' => 'أحمر فاتح',
    'LightYellow' => 'أصفر فاتح',
    'LightTeal' => 'سماوي',
    'Light' => 'أبيض فاتح',
    'PageColorChange' => 'تغير لون الصحفة',
    'ElementColorChange' => 'تغير لون العنصر',
    'ChangeMainFontColor' => 'تغير لون الخط الرئيسي',
    'SecondaryFontColorChange' => 'تغير لون الخط الثانوي',
    'ChangeFieldBackground' => 'تغير خلفية الحقول',
    'ChangeLogo' => 'تغير الشعار',
    'EnglishHotelName' => 'اسم الفندق الأجنبي',
    'ArabicHotelName' => 'اسم الفندق العربي',
    'ChooseYourColor' => 'اختر لونك',
    'AboutUs' => 'عن الفندق',
    'HotelImages' => 'صور الفندق',
    'EnglishAboutHotel' => 'حول الفندق أجنبي',
    'ArabicAboutHotel' => 'حول الفندق عربي',
    'DropFilesHereOrClickToUpload' => 'قم بإسقاط الملفات هنا أو انقر للتحميل',
    'RemoveFile' => 'حذف الملف',

    // Admin Floors Page
    'Floor' => 'طابق',
    'FloorId' => 'رقم الطابق',
    'FlatCount' => 'عدد الشقق',
    'AddedBy' => 'أضيف من قبل',
    'Processes' => 'العمليات',
    'NewFloor' => 'طابق جديد',
    'RemoveAFloor' => 'حذف الطابق',
    'Warning:AreYouSureAboutThat' => 'تحذير: هل أنت متأكد من ذلك',
    'AddNow' => 'أضف الآن',

    // Flat Admin Page
    'Flats' => 'الشقق',
    'Flat' => 'الشقة',
    'FlatId' => 'رقم الشقة',
    'AddFlat' => 'إضافة شقة',
    'RoomsCount' => 'عدد الغرف',
    'BedsCount' => 'عدد التخوت',
    'View' => 'الإطلالة',
    'FlatArea' => 'مساحة الشقة',
    'NewFlat' => 'شقة جديدة',
    'North' => 'الشمال',
    'East' => 'الشرق',
    'South' => 'الجنوب',
    'West' => 'الغرب',
    'NorthEast' => 'شمال شرق',
    'EastSouth' => 'جنوب شرق',
    'SouthWest' => 'جنوب غرب',
    'WestNorth' => 'شمال غرب',
    'MainImage' => 'الصورة الريئسية',
    'OtherImage' => 'صور ملحقة',
    'Close' => 'إغلاق',
    'Save' => 'حفظ',
    'Warning' => 'تحذير',
    'Quantity' => 'الكمية',
    'Warning:NoHotelFeaturesHaveBeenIntroducedYet' => 'تحذير: لم يتم إدخال الميزات الأساسية للفندق',
    'FlatFeatures' => 'ميزات الشقة:',
    'Warning:NoPrimaryFeaturesHaveBeenSelectedYet.' => '.تحذير: لم يتم إختيار ميزات الغرفة الأساسية بعد',

    // Features Admin Page
    'NewFeature' => 'ميزة جديدة',
    'AddFeature' => 'إضافة ميزة',
    'EditFeature' => 'تعديل الميزة',
    'FeatureId' => 'رقم الميزة',
    'FeatureName' => 'اسم الميزة',
    'Details' => 'التفاصيل',
    'LowPrice' => 'أدنى سعر',
    'HeighPrice' => 'أعلى سعر',
    'All' => 'الكل',
    'Room' => 'غرفة',
    'Bath' => 'حمام',
    'Bed' => 'سرير',
    'TV' => 'تلفاز',
    'AC' => 'مكيف',
    'Stove' => 'غاز',
    'Oven' => 'فرن',
    'Fridge' => 'براد',
    'Laundry' => 'غسالة',
    'Cooler' => 'مبرد',
    'ThisFeatureIsExsist' => 'هذه الميزة موجودة',
    'TheFeatureUsedInTheFlatCannotBeDeleted' => 'لا يمكن حذف هذه الميزة لأنها مضافة لشقق',

    // Employees Page
    'EmpId' => 'رقم الموظف',
    'NewEmployee' => 'موظف جديد',
    'EditEmployee' => 'تعديل موظف',
    'ThisUserNameIsExsist' => 'هذا الحساب موجود',

    // Services Page
    'ServiceId' => 'رقم الخدمة',
    'ServiceName' => 'اسم الخدمة',
    'NewService' => 'خدمة جديدة',

    // LogIn Page
    'UserName' => 'اسم المستخدم',
    'Password' => 'كلمة المرور',
    'Sorry:ThereIsAnErrorInTheUserNameOrPassword' => 'عذرا: هناك خطأ في اسم المستخدم أو كلمة المرور',

    // NotFound Page
    'notFound' => 'غير موجود',
    'Error' => 'خطأ',
    'GoBack' => 'رجوع للخلف',
    'ThePageYouWereLookingForDoesNotExist,TheAddressMayBeMisspelled,OrThePageMayHaveBeenMovedOrDeleted.' => 'الصفحة التي كنت تبحث عنها غير موجودة أو ربما أخطأت في كتابة العنوان أو ربما تكون الصفحة قد نُقِلت أو حُذِفت.',
    'ThePageDoesNotExist' => 'الصفحة غير موجودة',

    //Table
    'Search' => 'بحث',
    'ElemnetsOnEachPage' => 'عناصر بكل صفحة',
    'ThereAreNoResult' => 'لا يوجد نتائج',
    'From' => 'من',
    'OutOf' => 'من أصل',
    'Records' => 'سجلات',
    'Searched' => 'تم البحث فيها',

    // Home Page
    'Hotel' => 'الفندق',
    'HomePage' => 'الصفحة الرئيسية',
    'NotRated' => 'لم يتم تقييمه ',
    'Rate' => 'التقييم',
    'Search' => 'البحث',

    // Single Flat Page
    'BookingNow' => 'احجز الآن',
    'NationalId' => 'رقم الوطني',
    'IDImage' => 'صورة الهوية',
    'ChangeAccountImage' => 'تعديل صورة الحساب',
    'FlatRates' => 'تقييم الشقة',
    'EntryDate' => 'تاريخ الدخول',
    'ExitDate' => 'تاريخ الخروج',
    'ReadMore' => 'عرض المزيد',
    'ReadLess' => 'عرض أقل',
    'Cancel' => 'إلغاء الأمر',
    'FlatInformation' => 'معلومات الشقة',
    'FlatInfo' => ':خصائص الشقة',
    'FlatImages' => ':صور الشقة',
    'BookingDone' => 'تم الحجز',
    'BookingWait' => 'إنتطار الحجز',
    'ThisFlatIdIsAlreadyExistOnThisFloor' => 'رقم الشقة موجود في هذا الطابق',


    // Footer
    'HotelName' => 'دارنا أوتيل',
    'InformationAboutTheCompany' => 'معلومات عن الشركة',
    'Help' => 'مساعدة',
    'InformationOffice' => 'المكتب الاعلامي',
    'InvestorRelations' => 'علاقات المستثمرين',
    'LearnHowAWebsiteWorks' => 'تعرف على كيفية عمل موقع ',
    'TermsAndConditions' => 'الشروط و الاحكام',
    'LegalInformation' => 'المعلومات القانونية ',
    'PrivacyNotice' => 'إخطار الخصوصية',
    'SiteMap' => 'خريطة الموقع',
    'Copyrights' => 'حقوق ملكية',
    'AllRightsAreSave' => 'جميع الحفوف محفوظة',
  );
?>